ARG VERSION="42"
FROM registry.fedoraproject.org/fedora-toolbox:${VERSION}

# Build tools
RUN dnf install gcc -y && dnf clean all

# shell stuff
RUN dnf install fish neovim fzf jq gh -y && dnf clean all

# tools that should be run on host system are proxied
RUN echo 'flatpak-spawn --host podman "$@"' > "/usr/bin/podman" && chmod +x "/usr/bin/podman"
RUN echo 'flatpak-spawn --host notify-send "$@"' > "/usr/bin/notify-send" && chmod +x "/usr/bin/notify-send"
