ARG VERSION="40"
FROM registry.fedoraproject.org/fedora-toolbox:${VERSION}

# Build tools
RUN dnf install gcc -y && dnf clean all

# shell stuff
RUN dnf install fish neovim fzf -y && dnf clean all

RUN echo 'flatpak-spawn --host podman "$@"' > "/usr/bin/podman" && chmod +x "/usr/bin/podman"
