FROM quay.io/toolbx/ubuntu-toolbox:22.04

# install software-properties-common
RUN apt-get update \
    && apt-get --yes --install-recommends install software-properties-common \
    && apt-get clean && rm -rf /var/lib/apt/lists/*;

# install fish shell
RUN apt-add-repository ppa:fish-shell/release-3 \
    && apt-get update \
    && apt-get --yes --install-recommends install fish=3.6.1-1~jammy \
    && apt-get clean && rm -rf /var/lib/apt/lists/*;

# install neovim into /opt and symlink it to /usr/bin
RUN curl --location "https://github.com/neovim/neovim/releases/download/v0.9.2/nvim-linux64.tar.gz" --output nvim-linux64.tar.gz \
    && tar -xf nvim-linux64.tar.gz -C /opt \
    && rm nvim-linux64.tar.gz \
    && ln -s /opt/nvim-linux64/bin/nvim /usr/bin/nvim

